- hosts: miniserver
  pre_tasks:
    - name: Get host IP
      shell: hostname -I | awk '{print $1}'
      register: hostip_cmd
  vars:
    hostip: "{{ hostip_cmd.stdout }}"
    homedir: "{{ lookup('env', 'HOME') }}"
    datadir: "/mnt/data"
    
  roles:
    - base
    - nextcloud
    - samba-share
  #   - dotfiles
  #   - docker
  #   - raiddatastorage
  #   - raidbackup
  #   - disk standby services