---
- name: Install required deb packages
  become: yes
  ansible.builtin.apt:
    pkg:
      - fdisk
      - hdparm
      - rsync
      - sysstat
      - e2fsprogs
      - smartmontools
      - mdadm
    state: present
    install_recommends: no
    update_cache: yes